=begin
#Moosend API

#TODO: Add a description

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CampaignsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CampaignsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CampaignsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CampaignsApi' do
    it 'should create an instance of CampaignsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CampaignsApi)
    end
  end

  # unit tests for a_b_test_campaign_summary
  # AB Test Campaign Summary
  # Provides a basic summary of the results for a sent AB test campaign, separately for each version (A and B), such as the number of recipients, opens, clicks, bounces, unsubscribes, forwards etc to date.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param campaign_id The ID of the requested AB test campaign
  # @param [Hash] opts the optional parameters
  # @return [AbTestCampaignSummaryResponse]
  describe 'a_b_test_campaign_summary test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for activity_by_location
  # Activity By Location
  # Returns a detailed report of your campaign opens (unique and total) by country.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param campaign_id The ID of the requested campaign
  # @param [Hash] opts the optional parameters
  # @return [ActivityByLocationResponse]
  describe 'activity_by_location test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for campaign_summary
  # Campaign Summary
  # Provides a basic summary of the results for any sent campaign such as the number of recipients, opens, clicks, bounces, unsubscribes, forwards etc. to date.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param campaign_id The ID of the requested campaign
  # @param [Hash] opts the optional parameters
  # @return [CampaignSummaryResponse]
  describe 'campaign_summary test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cloning_an_existing_campaign
  # Cloning An Existing Campaign
  # Creates an exact copy of an existing campaign. The new campaign is created as a draft.
  # @param format 
  # @param campaign_id 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param [Hash] opts the optional parameters
  # @return [CloningAnExistingCampaignResponse]
  describe 'cloning_an_existing_campaign test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for creating_a_draft_campaign
  # Creating A Draft Campaign
  # Creates a new campaign in your account. This method does not send the campaign, but rather creates it as a draft, ready for sending or testing.  You can choose to send either a regular campaign or an AB split campaign. Campaign content must be specified from a web location.  Ignore ***(A/B Split Campaign Option)*** if you want to create a regular campaign.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [CreatingADraftCampaignResponse]
  describe 'creating_a_draft_campaign test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deleting_a_campaign
  # Deleting A Campaign
  # Deletes a campaign from your account, draft or even sent.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param campaign_id The ID of the draft campaign to update.
  # @param [Hash] opts the optional parameters
  # @return [DeletingACampaignResponse]
  describe 'deleting_a_campaign test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_campaigns
  # Get All Campaigns
  # Returns a list of all campaigns in your account with detailed information. Because the results for this call could be quite big, paging information is required as input.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param [Hash] opts the optional parameters
  # @return [GetAllCampaignsResponse]
  describe 'get_all_campaigns test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_campaign_statistics_with_paging__filtered
  # Get Campaign Statistics With Paging &amp; Filtered
  # Returns a detailed list of statistics for a given campaign based on activity such as emails sent, opened, bounced, link clicked, etc.  Because the results for this call could be quite big, paging information is required as input.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param campaign_id The ID of the requested AB test campaign
  # @param type The type of the activity to display results for. This must be one of the following values : * Sent : To get information about when and to which recipients the campaign was sent. * Opened : To get information about who opened the campaign. * LinkClicked : To get information about who clicked on which link. * Forward : To get information about who forwarded the campaign using the relevant link on the email body and when. * Unsubscribed : To get information about who unsubscribed from the campaign by clicking on the unsubscribe link and when. * Bounced : To get information about which email recipients failed to receive the campaign. If not specified, the value Sent will be used by default.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page The page number to display results for. If not specified, the first page will be returned.
  # @option opts [String] :page_size The maximum number of results per page. This must be a positive integer up to 100. If not specified, 50 results per page will be returned.  If a value greater than 100 is specified, it will be treated as 100.
  # @option opts [String] :from A date value that specifies since when to start returning results. If omitted, results will be returned from the moment the campaign was sent.
  # @option opts [String] :to A date value that specifies up to when to return results. If omitted, results will be returned up to date.
  # @return [GetCampaignStatisticsWithPagingFilteredResponse]
  describe 'get_campaign_statistics_with_paging__filtered test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_campaigns_by_page
  # Get Campaigns By Page
  # Returns a list of all campaigns in your account with detailed information. Because the results for this call could be quite big, paging information is required as input.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param page The page number to display results for.
  # @param [Hash] opts the optional parameters
  # @return [GetCampaignsByPageResponse]
  describe 'get_campaigns_by_page test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_campaigns_by_page_and_pagesize
  # Get Campaigns By Page And Pagesize
  # Returns a list of all campaigns in your account with detailed information. Because the results for this call could be quite big, paging information is required as input.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param page The page number to display results for.
  # @param page_size The maximum number of results per page.  This must be a positive integer up to 100. If not specified, 50 results per page will be returned.  If a value greater than 100 is specified, it will be treated as 100.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :short_by The name of the campaign property to sort results by. If not specified, results will be sorted by the CreatedOn property
  # @option opts [String] :sort_method The method to sort results: ASC for ascending, DESC for descending. If not specified, &#x60;ASC&#x60; will be assumed
  # @return [GetCampaignsByPageAndPagesizeResponse]
  describe 'get_campaigns_by_page_and_pagesize test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getting_all_your_senders
  # Getting All Your Senders
  # Gets a list of your active senders in your account. You may specify any email address of these senders when sending a campaign.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param [Hash] opts the optional parameters
  # @return [GettingAllYourSendersResponse]
  describe 'getting_all_your_senders test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getting_campaign_details
  # Getting Campaign Details
  # Returns a complete set of properties that describe the requested campaign in detail. No statistics are included in the result.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param campaign_id The ID of the requested campaign
  # @param [Hash] opts the optional parameters
  # @return [GettingCampaignDetailsResponse]
  describe 'getting_campaign_details test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getting_sender_details
  # Getting Sender Details
  # Returns basic information for the specified sender identified by its email address.
  # @param format 
  # @param email 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param [Hash] opts the optional parameters
  # @return [GettingSenderDetailsResponse]
  describe 'getting_sender_details test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for link_activity
  # Link Activity
  # Returns a list with your campaign links and how many clicks have been made by your recipients, either unique or total.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param campaign_id The ID of the requested campaign
  # @param [Hash] opts the optional parameters
  # @return [LinkActivityResponse]
  describe 'link_activity test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for scheduling_a_campaign
  # Scheduling A Campaign
  # Assigns a scheduled date and time at which the campaign will be delivered.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param campaign_id The ID of the campaign to be scheduled
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [SchedulingACampaignResponse]
  describe 'scheduling_a_campaign test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sending_a_campaign
  # Sending a campaign
  # Sends an existing draft campaign to all recipients specified in its mailing list. The campaign is sent immediatelly.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param campaign_id The ID of the draft campaign to be sent.
  # @param [Hash] opts the optional parameters
  # @return [SendingACampaignResponse]
  describe 'sending_a_campaign test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for testing_a_campaign
  # Testing a campaign
  # Sends a test email of a draft campaign to a list of email addresses you specify for previewing.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param campaign_id The ID of the draft campaign to be tested.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [TestingACampaignResponse]
  describe 'testing_a_campaign test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for unscheduling_a_campaign
  # Unscheduling a campaign
  # Removes a previously defined scheduled date and time from a campaign, so that it will be delivered immediately if already queued or when sent.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param campaign_id The ID of the campaign to be scheduled
  # @param [Hash] opts the optional parameters
  # @return [UnschedulingACampaignResponse]
  describe 'unscheduling_a_campaign test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for updating_a_draft_campaign
  # Updating A Draft Campaign
  # Updates properties of an existing draft A/B campaign in your account. Non-draft campaigns cannot be updated. Ignore ***(A/B Split Campaign Option)*** if you want to create a regular campaign.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param campaign_id The ID of the draft campaign to update.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [UpdatingADraftCampaignResponse]
  describe 'updating_a_draft_campaign test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
