=begin
#Moosend API

#TODO: Add a description

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MailingListsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MailingListsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MailingListsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MailingListsApi' do
    it 'should create an instance of MailingListsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MailingListsApi)
    end
  end

  # unit tests for creating_a_custom_field
  # Creating a custom field
  # Creates a new custom field in the specified mailing list.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param mailing_list_id The ID of the mailing list where the custom field will belong.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [CreatingACustomFieldResponse]
  describe 'creating_a_custom_field test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for creating_a_mailing_list
  # Creating a mailing list
  # Creates a new empty mailing list in your account.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [CreatingAMailingListResponse]
  describe 'creating_a_mailing_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deleting_a_mailing_list
  # Deleting a mailing list
  # Deletes a mailing list from your account.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param mailing_list_id The ID of the mailing list to be deleted.
  # @param [Hash] opts the optional parameters
  # @return [DeletingAMailingListResponse]
  describe 'deleting_a_mailing_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getting_all_active_mailing_lists
  # Getting all active mailing lists
  # Gets a list of your active mailing lists in your account.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :with_statistics Specifies whether to fetch statistics for the subscribers or not. If omitted, results will be returned with statistics by default.
  # @option opts [String] :short_by The name of the campaign property to sort results by. If not specified, results will be sorted by the CreatedOn property
  # @option opts [String] :sort_method The method to sort results: ASC for ascending, DESC for descending. If not specified, &#x60;ASC&#x60; will be assumed
  # @return [GettingAllActiveMailingListsResponse]
  describe 'getting_all_active_mailing_lists test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getting_all_active_mailing_lists_with_paging
  # Getting all active mailing lists with paging
  # Gets a list of your active mailing lists in your account. Because the results for this call could be quite big, paging information is required as input.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param page The page that you want to get.
  # @param page_size Lists Per Page.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :short_by The name of the campaign property to sort results by. If not specified, results will be sorted by the CreatedOn property
  # @option opts [String] :sort_method The method to sort results: ASC for ascending, DESC for descending. If not specified, &#x60;ASC&#x60; will be assumed
  # @return [GettingAllActiveMailingListsWithPagingResponse]
  describe 'getting_all_active_mailing_lists_with_paging test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getting_mailing_list_details
  # Getting mailing list details
  # Gets details for a given mailing list. You may include subscriber statistics in your results or not. Any segments existing for the requested mailing list will not be included in the results.
  # @param format 
  # @param mailing_list_id The ID of the mailing list to be returned.
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :with_statistics Specifies whether to fetch statistics for the subscribers or not. If omitted, results will be returned with statistics by default.
  # @return [GettingMailingListDetailsResponse]
  describe 'getting_mailing_list_details test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for removing_a_custom_field
  # Removing a custom field
  # Removes a custom field definition from the specified mailing list.
  # @param format 
  # @param custom_field_id The ID of the custom field to be deleted.
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param mailing_list_id The ID of the mailing list where the custom field belongs.
  # @param [Hash] opts the optional parameters
  # @return [RemovingACustomFieldResponse]
  describe 'removing_a_custom_field test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for updating_a_custom_field
  # Updating a custom field
  # Updates the properties of an existing custom field in the specified mailing list.
  # @param format 
  # @param custom_field_id The ID of the custom field to be updated.
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param mailing_list_id The ID of the mailing list where the custom field belongs.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [UpdatingACustomFieldResponse]
  describe 'updating_a_custom_field test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for updating_a_mailing_list
  # Updating a mailing list
  # Updates the properties of an existing mailing list.
  # @param format 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param mailing_list_id The ID of the mailing list to be updated.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [UpdatingAMailingListResponse]
  describe 'updating_a_mailing_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
