=begin
#Moosend API

#TODO: Add a description

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SegmentsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SegmentsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SegmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SegmentsApi' do
    it 'should create an instance of SegmentsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SegmentsApi)
    end
  end

  # unit tests for adding_criteria_to_segments
  # Adding criteria to segments
  # Adds a new criterion (a rule) to the specified segment.
  # @param format 
  # @param mailing_list_id The ID of the mailing list the specified segment belongs.
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param segment_id The ID of the segment to update.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [AddingCriteriaToSegmentsResponse]
  describe 'adding_criteria_to_segments test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for creating_a_new_segment
  # Creating a new segment
  # Creates a new empty segment (without criteria) for the given mailing list. You may specify the name of the segment and the way the criteria will match together.
  # @param format 
  # @param mailing_list_id The ID of the mailing list the specified segment belongs
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [CreatingANewSegmentResponse]
  describe 'creating_a_new_segment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deleting_a_segment
  # Deleting A Segment
  # Deletes a segment along with its criteria from the mailing list. The subscribers of the mailing list that the segment returned are not deleted or affected in any way.
  # @param format 
  # @param mailing_list_id The ID of the mailing list the specified segment belongs.
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param segment_id The ID of the segment to update.
  # @param [Hash] opts the optional parameters
  # @return [DeletingASegmentResponse]
  describe 'deleting_a_segment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getting_segment_details
  # Getting segment details
  # Gets detailed information on a specific segment and its criteria. However, it does not include the subscribers returned by the segment.
  # @param format 
  # @param mailing_list_id The ID of the mailing list the specified segment belongs
  # @param segment_id The ID of the segment to fetch results for.
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param [Hash] opts the optional parameters
  # @return [GettingSegmentDetailsResponse]
  describe 'getting_segment_details test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getting_segment_subscribers
  # Getting segment subscribers
  # Gets a list of the subscribers that the specified segment returns according to its criteria. Because the results for this call could be quite big, paging information is required as input.
  # @param format 
  # @param mailing_list_id The ID of the mailing list the specified segment belongs
  # @param segment_id The ID of the segment to fetch results for.
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param [Hash] opts the optional parameters
  # @return [GettingSegmentSubscribersResponse]
  describe 'getting_segment_subscribers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getting_segments
  # Getting segments
  # Get a list of all segments with their criteria for the given mailing list.
  # @param format 
  # @param mailing_list_id 
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param [Hash] opts the optional parameters
  # @return [GettingSegmentsResponse]
  describe 'getting_segments test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for updating_a_segment
  # Updating a segment
  # Updates the properties of an existing segment. You may update the name and match type of the segment.
  # @param format 
  # @param mailing_list_id The ID of the mailing list the specified segment belongs
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param segment_id The ID of the segment to update.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [UpdatingASegmentResponse]
  describe 'updating_a_segment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for updating_segment_criteria
  # Updating segment criteria
  # Updates an existing criterion in the specified segment.
  # @param format 
  # @param mailing_list_id The ID of the mailing list the specified segment belongs.
  # @param apikey You may find your API Key or generate a new one in your account settings.
  # @param segment_id The ID of the segment to update.
  # @param criteria_id The ID of the criterion to process.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [UpdatingSegmentCriteriaResponse]
  describe 'updating_segment_criteria test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
