=begin
#Moosend API

#TODO: Add a description

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::WithStatistics
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WithStatistics' do
  before do
    # run before each test
    @instance = SwaggerClient::WithStatistics.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WithStatistics' do
    it 'should create an instance of WithStatistics' do
      expect(@instance).to be_instance_of(SwaggerClient::WithStatistics)
    end
  end
end

