=begin
#Moosend API

#TODO: Add a description

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'date'

module SwaggerClient

  class ABCampaignData
    # 
    attr_accessor :ab_campaign_type

    # 
    attr_accessor :ab_winner_selection_type

    # 
    attr_accessor :delivered_on_a

    # 
    attr_accessor :delivered_on_b

    # 
    attr_accessor :html_content_b

    # 
    attr_accessor :hours_to_test

    # 
    attr_accessor :id

    # 
    attr_accessor :list_percentage

    # 
    attr_accessor :plain_content_b

    # 
    attr_accessor :sender_b

    # 
    attr_accessor :subject_b

    # 
    attr_accessor :web_location_b


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ab_campaign_type' => :'ABCampaignType',
        :'ab_winner_selection_type' => :'ABWinnerSelectionType',
        :'delivered_on_a' => :'DeliveredOnA',
        :'delivered_on_b' => :'DeliveredOnB',
        :'html_content_b' => :'HTMLContentB',
        :'hours_to_test' => :'HoursToTest',
        :'id' => :'ID',
        :'list_percentage' => :'ListPercentage',
        :'plain_content_b' => :'PlainContentB',
        :'sender_b' => :'SenderB',
        :'subject_b' => :'SubjectB',
        :'web_location_b' => :'WebLocationB'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'ab_campaign_type' => :'Float',
        :'ab_winner_selection_type' => :'Float',
        :'delivered_on_a' => :'String',
        :'delivered_on_b' => :'String',
        :'html_content_b' => :'String',
        :'hours_to_test' => :'Float',
        :'id' => :'Float',
        :'list_percentage' => :'Float',
        :'plain_content_b' => :'String',
        :'sender_b' => :'String',
        :'subject_b' => :'String',
        :'web_location_b' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'ABCampaignType')
        self.ab_campaign_type = attributes[:'ABCampaignType']
      end

      if attributes.has_key?(:'ABWinnerSelectionType')
        self.ab_winner_selection_type = attributes[:'ABWinnerSelectionType']
      end

      if attributes.has_key?(:'DeliveredOnA')
        self.delivered_on_a = attributes[:'DeliveredOnA']
      end

      if attributes.has_key?(:'DeliveredOnB')
        self.delivered_on_b = attributes[:'DeliveredOnB']
      end

      if attributes.has_key?(:'HTMLContentB')
        self.html_content_b = attributes[:'HTMLContentB']
      end

      if attributes.has_key?(:'HoursToTest')
        self.hours_to_test = attributes[:'HoursToTest']
      end

      if attributes.has_key?(:'ID')
        self.id = attributes[:'ID']
      end

      if attributes.has_key?(:'ListPercentage')
        self.list_percentage = attributes[:'ListPercentage']
      end

      if attributes.has_key?(:'PlainContentB')
        self.plain_content_b = attributes[:'PlainContentB']
      end

      if attributes.has_key?(:'SenderB')
        self.sender_b = attributes[:'SenderB']
      end

      if attributes.has_key?(:'SubjectB')
        self.subject_b = attributes[:'SubjectB']
      end

      if attributes.has_key?(:'WebLocationB')
        self.web_location_b = attributes[:'WebLocationB']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ab_campaign_type == o.ab_campaign_type &&
          ab_winner_selection_type == o.ab_winner_selection_type &&
          delivered_on_a == o.delivered_on_a &&
          delivered_on_b == o.delivered_on_b &&
          html_content_b == o.html_content_b &&
          hours_to_test == o.hours_to_test &&
          id == o.id &&
          list_percentage == o.list_percentage &&
          plain_content_b == o.plain_content_b &&
          sender_b == o.sender_b &&
          subject_b == o.subject_b &&
          web_location_b == o.web_location_b
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [ab_campaign_type, ab_winner_selection_type, delivered_on_a, delivered_on_b, html_content_b, hours_to_test, id, list_percentage, plain_content_b, sender_b, subject_b, web_location_b].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
