=begin
#Moosend API

#TODO: Add a description

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'date'

module SwaggerClient

  class Context93
    attr_accessor :ab_campaign_data

    # 
    attr_accessor :confirmation_to

    # 
    attr_accessor :created_on

    # 
    attr_accessor :delivered_on

    # 
    attr_accessor :format_type

    # 
    attr_accessor :html_content

    # 
    attr_accessor :id

    # 
    attr_accessor :is_transactional

    # 
    attr_accessor :mailing_lists

    # 
    attr_accessor :name

    # 
    attr_accessor :plain_content

    attr_accessor :reply_to_email

    # 
    attr_accessor :scheduled_for

    attr_accessor :sender

    # 
    attr_accessor :status

    # 
    attr_accessor :subject

    # 
    attr_accessor :timezone

    # 
    attr_accessor :updated_on

    # 
    attr_accessor :web_location


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ab_campaign_data' => :'ABCampaignData',
        :'confirmation_to' => :'ConfirmationTo',
        :'created_on' => :'CreatedOn',
        :'delivered_on' => :'DeliveredOn',
        :'format_type' => :'FormatType',
        :'html_content' => :'HTMLContent',
        :'id' => :'ID',
        :'is_transactional' => :'IsTransactional',
        :'mailing_lists' => :'MailingLists',
        :'name' => :'Name',
        :'plain_content' => :'PlainContent',
        :'reply_to_email' => :'ReplyToEmail',
        :'scheduled_for' => :'ScheduledFor',
        :'sender' => :'Sender',
        :'status' => :'Status',
        :'subject' => :'Subject',
        :'timezone' => :'Timezone',
        :'updated_on' => :'UpdatedOn',
        :'web_location' => :'WebLocation'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'ab_campaign_data' => :'ABCampaignData',
        :'confirmation_to' => :'String',
        :'created_on' => :'String',
        :'delivered_on' => :'String',
        :'format_type' => :'Float',
        :'html_content' => :'String',
        :'id' => :'String',
        :'is_transactional' => :'BOOLEAN',
        :'mailing_lists' => :'Array<MailingList85>',
        :'name' => :'String',
        :'plain_content' => :'String',
        :'reply_to_email' => :'ReplyToEmail',
        :'scheduled_for' => :'String',
        :'sender' => :'Sender',
        :'status' => :'Float',
        :'subject' => :'String',
        :'timezone' => :'String',
        :'updated_on' => :'String',
        :'web_location' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'ABCampaignData')
        self.ab_campaign_data = attributes[:'ABCampaignData']
      end

      if attributes.has_key?(:'ConfirmationTo')
        self.confirmation_to = attributes[:'ConfirmationTo']
      end

      if attributes.has_key?(:'CreatedOn')
        self.created_on = attributes[:'CreatedOn']
      end

      if attributes.has_key?(:'DeliveredOn')
        self.delivered_on = attributes[:'DeliveredOn']
      end

      if attributes.has_key?(:'FormatType')
        self.format_type = attributes[:'FormatType']
      end

      if attributes.has_key?(:'HTMLContent')
        self.html_content = attributes[:'HTMLContent']
      end

      if attributes.has_key?(:'ID')
        self.id = attributes[:'ID']
      end

      if attributes.has_key?(:'IsTransactional')
        self.is_transactional = attributes[:'IsTransactional']
      end

      if attributes.has_key?(:'MailingLists')
        if (value = attributes[:'MailingLists']).is_a?(Array)
          self.mailing_lists = value
        end
      end

      if attributes.has_key?(:'Name')
        self.name = attributes[:'Name']
      end

      if attributes.has_key?(:'PlainContent')
        self.plain_content = attributes[:'PlainContent']
      end

      if attributes.has_key?(:'ReplyToEmail')
        self.reply_to_email = attributes[:'ReplyToEmail']
      end

      if attributes.has_key?(:'ScheduledFor')
        self.scheduled_for = attributes[:'ScheduledFor']
      end

      if attributes.has_key?(:'Sender')
        self.sender = attributes[:'Sender']
      end

      if attributes.has_key?(:'Status')
        self.status = attributes[:'Status']
      end

      if attributes.has_key?(:'Subject')
        self.subject = attributes[:'Subject']
      end

      if attributes.has_key?(:'Timezone')
        self.timezone = attributes[:'Timezone']
      end

      if attributes.has_key?(:'UpdatedOn')
        self.updated_on = attributes[:'UpdatedOn']
      end

      if attributes.has_key?(:'WebLocation')
        self.web_location = attributes[:'WebLocation']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ab_campaign_data == o.ab_campaign_data &&
          confirmation_to == o.confirmation_to &&
          created_on == o.created_on &&
          delivered_on == o.delivered_on &&
          format_type == o.format_type &&
          html_content == o.html_content &&
          id == o.id &&
          is_transactional == o.is_transactional &&
          mailing_lists == o.mailing_lists &&
          name == o.name &&
          plain_content == o.plain_content &&
          reply_to_email == o.reply_to_email &&
          scheduled_for == o.scheduled_for &&
          sender == o.sender &&
          status == o.status &&
          subject == o.subject &&
          timezone == o.timezone &&
          updated_on == o.updated_on &&
          web_location == o.web_location
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [ab_campaign_data, confirmation_to, created_on, delivered_on, format_type, html_content, id, is_transactional, mailing_lists, name, plain_content, reply_to_email, scheduled_for, sender, status, subject, timezone, updated_on, web_location].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
