=begin
#Moosend API

#TODO: Add a description

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'date'

module SwaggerClient
  class ShortBy
    
    NAME = "Name".freeze
    SUBJECT = "Subject".freeze
    STATUS = "Status".freeze
    DELIVERED_ON = "DeliveredOn".freeze
    CREATED_ON = "CreatedOn".freeze
  end

end
