=begin
#Moosend API

#TODO: Add a description

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'date'

module SwaggerClient
  class Type
    
    SENT = "Sent".freeze
    OPENED = "Opened".freeze
    LINK_CLICKED = "LinkClicked".freeze
    FORWARD = "Forward".freeze
    UNSUBSCRIBED = "Unsubscribed".freeze
    BOUNCED = "Bounced".freeze
  end

end
