=begin
#Moosend API

#TODO: Add a description

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'date'

module SwaggerClient
  class WithStatistics
    
    TRUE = "true".freeze
    FALSE = "false".freeze
  end

end
