=begin
#Moosend API

#TODO: Add a description

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/a'
require 'swagger_client/models/ab_campaign_data'
require 'swagger_client/models/ab_test_campaign_summary_response'
require 'swagger_client/models/activity_by_location_response'
require 'swagger_client/models/adding_criteria_to_segments_request'
require 'swagger_client/models/adding_criteria_to_segments_response'
require 'swagger_client/models/adding_multiple_subscribers_request'
require 'swagger_client/models/adding_multiple_subscribers_response'
require 'swagger_client/models/adding_subscribers_request'
require 'swagger_client/models/adding_subscribers_response'
require 'swagger_client/models/analytic'
require 'swagger_client/models/b'
require 'swagger_client/models/campaign'
require 'swagger_client/models/campaign_summary_response'
require 'swagger_client/models/cloning_an_existing_campaign_response'
require 'swagger_client/models/context'
require 'swagger_client/models/context110'
require 'swagger_client/models/context118'
require 'swagger_client/models/context132'
require 'swagger_client/models/context140'
require 'swagger_client/models/context145'
require 'swagger_client/models/context148'
require 'swagger_client/models/context17'
require 'swagger_client/models/context32'
require 'swagger_client/models/context37'
require 'swagger_client/models/context52'
require 'swagger_client/models/context64'
require 'swagger_client/models/context66'
require 'swagger_client/models/context72'
require 'swagger_client/models/context84'
require 'swagger_client/models/context89'
require 'swagger_client/models/context93'
require 'swagger_client/models/creating_a_custom_field_request'
require 'swagger_client/models/creating_a_custom_field_response'
require 'swagger_client/models/creating_a_draft_campaign_request'
require 'swagger_client/models/creating_a_draft_campaign_response'
require 'swagger_client/models/creating_a_mailing_list_request'
require 'swagger_client/models/creating_a_mailing_list_response'
require 'swagger_client/models/creating_a_new_segment_request'
require 'swagger_client/models/creating_a_new_segment_response'
require 'swagger_client/models/criterion'
require 'swagger_client/models/custom_field'
require 'swagger_client/models/custom_field53'
require 'swagger_client/models/custom_fields_definition'
require 'swagger_client/models/deleting_a_campaign_response'
require 'swagger_client/models/deleting_a_mailing_list_response'
require 'swagger_client/models/deleting_a_segment_response'
require 'swagger_client/models/format'
require 'swagger_client/models/get_all_campaigns_response'
require 'swagger_client/models/get_campaign_statistics_response'
require 'swagger_client/models/get_campaign_statistics_with_paging_filtered_response'
require 'swagger_client/models/get_campaigns_by_page_and_pagesize_response'
require 'swagger_client/models/get_campaigns_by_page_response'
require 'swagger_client/models/get_subscriber_by_email_address_response'
require 'swagger_client/models/get_subscriber_by_id_response'
require 'swagger_client/models/getting_all_active_mailing_lists_response'
require 'swagger_client/models/getting_all_active_mailing_lists_with_paging_response'
require 'swagger_client/models/getting_all_your_senders_response'
require 'swagger_client/models/getting_campaign_details_response'
require 'swagger_client/models/getting_mailing_list_details_response'
require 'swagger_client/models/getting_segment_details_response'
require 'swagger_client/models/getting_segment_subscribers_response'
require 'swagger_client/models/getting_segments_response'
require 'swagger_client/models/getting_sender_details_response'
require 'swagger_client/models/getting_subscribers_response'
require 'swagger_client/models/import_operation'
require 'swagger_client/models/import_operation19'
require 'swagger_client/models/link_activity_response'
require 'swagger_client/models/mailing_list'
require 'swagger_client/models/mailing_list68'
require 'swagger_client/models/mailing_list69'
require 'swagger_client/models/mailing_list85'
require 'swagger_client/models/mailing_lists'
require 'swagger_client/models/mailing_lists119'
require 'swagger_client/models/mailing_lists134'
require 'swagger_client/models/paging'
require 'swagger_client/models/paging76'
require 'swagger_client/models/removing_a_custom_field_response'
require 'swagger_client/models/removing_a_subscriber_request'
require 'swagger_client/models/removing_a_subscriber_response'
require 'swagger_client/models/removing_multiple_subscribers_request'
require 'swagger_client/models/removing_multiple_subscribers_response'
require 'swagger_client/models/reply_to_email'
require 'swagger_client/models/scheduling_a_campaign_request'
require 'swagger_client/models/scheduling_a_campaign_response'
require 'swagger_client/models/segment'
require 'swagger_client/models/sender'
require 'swagger_client/models/sending_a_campaign_response'
require 'swagger_client/models/short_by'
require 'swagger_client/models/sort_method'
require 'swagger_client/models/status'
require 'swagger_client/models/subscriber'
require 'swagger_client/models/subscribers'
require 'swagger_client/models/subscribers150'
require 'swagger_client/models/testing_a_campaign_request'
require 'swagger_client/models/testing_a_campaign_response'
require 'swagger_client/models/type'
require 'swagger_client/models/unscheduling_a_campaign_response'
require 'swagger_client/models/unsubscribing_subscribers_from_account_request'
require 'swagger_client/models/unsubscribing_subscribers_from_account_response'
require 'swagger_client/models/unsubscribing_subscribers_from_mailing_list_and_a_specified_campaign_request'
require 'swagger_client/models/unsubscribing_subscribers_from_mailing_list_and_a_specified_campaign_response'
require 'swagger_client/models/unsubscribing_subscribers_from_mailing_list_request'
require 'swagger_client/models/unsubscribing_subscribers_from_mailing_list_response'
require 'swagger_client/models/updating_a_custom_field_request'
require 'swagger_client/models/updating_a_custom_field_response'
require 'swagger_client/models/updating_a_draft_campaign_request'
require 'swagger_client/models/updating_a_draft_campaign_response'
require 'swagger_client/models/updating_a_mailing_list_request'
require 'swagger_client/models/updating_a_mailing_list_response'
require 'swagger_client/models/updating_a_segment_request'
require 'swagger_client/models/updating_a_segment_response'
require 'swagger_client/models/updating_a_subscriber_request'
require 'swagger_client/models/updating_a_subscriber_response'
require 'swagger_client/models/updating_segment_criteria_request'
require 'swagger_client/models/updating_segment_criteria_response'
require 'swagger_client/models/with_statistics'

# APIs
require 'swagger_client/api/campaigns_api'
require 'swagger_client/api/mailing_lists_api'
require 'swagger_client/api/segments_api'
require 'swagger_client/api/subscribers_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
